# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김규완
title: Security Engineer  
email: kukuwhy6@gmail.com
website: https://kukuwhy.github.io


# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kukuwhy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kyuxxn
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  제 이름은 김규완입니다. 저는 **서비스 보안 엔지니어**로 일하고 있습니다.  

  복잡하고 어려운 문제를 기술적인 자동화로 해결하는 것을 좋아합니다.

  서비스 보안 분야를 제외하고도 모든 보안 영역을 포함한 개발 및 인프라 기술에 관심이 많습니다.

  읽어주셔서 감사합니다.
  
  <br><br>
  PDF로 출력된 이력서가 읽기 힘드시다면 [링크](https://kukuwhy.github.io/Resume)로 접근해주세요.

content:
  - title: Key Expertise
    layout: text
    content: | # this will include new lines to allow paragraphs
      - API, Web/App(iOS,Android), C/S, IoT 취약점 점검
      - Web/App 소스코드 취약점 점검 
      - 시나리오 기반 인프라 모의침투
      - 보안 프로세스/취약점 점검 자동화 시스템 개발
      - K-Shield Jr. 11기 멘토
      - 인프라 취약점 점검(OS, Container, Image)
      - 커뮤니케이션 및 문서 작성

  - title: Skilled in Cybersecurity Tools and Environments
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>Firefox</mark> Chrome
      - <mark>Burpsuite</mark> <mark>OWASP ZAP</mark>
      - <mark>Python</mark> Shell Javascript
      - <mark>Insomnia</mark> <mark>jadx</mark> <mark>Hopper</mark>
      - <mark>Visual Studio Code</mark> Sublime Text Xcode Android Studio
      - <mark>Flask</mark> <mark>Git</mark> Active Directory
      - Jira Confluence
      - <mark>Google Cloud Platform</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 스윗코리아
        link: swit.io
        # link_text: boringcompany.com
        sub_title: 서비스 보안 매니저
        caption: 2022 - Present
        description: | 
            <b>Hackerone Bugbounty 운영</b>
            -	프로그램 정책 및 범위 수립
            -	보고서 검토/취약점 재현 및 영향도 평가
            -	취약점 조치 및 이슈 전달
            -	보상금 평가 및 수여
            -	Jira/Swit 이슈 추적 자동화 개발

            <b>서비스 모의해킹/취약점 점검</b>
            - 모의해킹 방법론 및 가이드 작성
            - 서비스 취약점 점검(Web/Mobile/Desktop)
            - 시나리오 기반 모의침투

            <b>보안성 검토</b>
            -	보안성 검토 지침/가이드 작성
            -	체크리스트 수립
            -	기획/개발/QA 단계 보안성 검토

            <b>위협 알람/액션 앱 개발</b>
            -	위협 이벤트 발생 시 Swit Developers App을 통한 알람 개발
            -	이벤트에 따른 액션 기능 개발(IP차단, 공격 Payload 확인, 검토 등록)
            -	Jira와 연동 되어 이슈 추적 기능 개발
            - GCP 인프라 설계

            <b>CI/CD 자동화 보안 프로세스 개발</b>
            -	정적 소스코드 취약점 점검(Sonarqube)
            -	동적 취약점 점검(OWASP ZAP)
            -	신규 API(staging, 운영) 및 신규 위협 파라미터(url, path 등) 이벤트 시스템
            -	GKE 이미지/런타임 취약점 점검 자동화

      - layout: left
        title: 시큐리티허브
        link: securityhub.co.kr
        sub_title: 보안 컨설턴트(모의해킹)
        caption: 2019 - 2022
        description: | # this will include new lines to allow paragraphs
            <b>시나리오 기반 모의침투</b>
            - 시나리오 작성
            - 정보 수집 및 초기 침투 
            - 내부 침투
            - 결과 보고서 작성
            - 자동화 도구 개발 및 적용

            <b>취약점 점검</b>
            - Web/Mobile/CS/IoT/Infra 취약점 점검
            - 결과보고서 작성
            



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 금오공과대학교
        caption: 2012 - 2019
        sub_title: 컴퓨터소프트웨어공학과
        description: | # this will include new
            <b>보안 동아리 창설 및 활동 - BOSS</b>
            - Nessus를 활용한 MetasploitableV3 취약점 분석 평가 보고서
            - 실시간 패킷 분석 시스템 개발 
            - NSE를 이용한 스크립트 분석 보고서 작성
            - The Lord Of Bufferoverflow 실습 보고서 작성
            - 내부 스터디 및 연구 진행

            <b>자연어처리 연구실 - 연구실장</b>
            - 문단 간 유사도와 로지스틱 회귀 분류를 통한 기사 내 부적합 문단 검출 시스템 개발 및 논문 작성
            - 자연어 처리 연구

      - layout: left
        title: 부일전자디자인고등학교
        caption: 2009 - 2012
        sub_title: 컴퓨터과
        description: | # this will include new
            <b>기능경기부 활동</b>
            - 웹 개발 학습(apache, mysql, php, photoshop)
            - 부산지방기능경기대회 은메달 입상

      - layout: left
        title: 정보보호 교육
        caption: 2018, 2011
        sub_title: 정보보호 관리진단 기술인력 양성 과정, 모의해킹, 정보보안 전문가
        description: | # this will include new
            <b>보안 교육 과정 수강</b>
            - K-Shield Jr. 1기 
            - 보안프로젝트 모의해킹 실무자 과정
            - i2sec 정보보안전문가 과정

  - title: Awards & ETC
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 네이버 버그바운티 제보 @NBB-1405-XSS
      - 정보처리기사 취득 @한국산업인력공단
      - 제1회 시큐리티허브 사내세미나 1위 @Docker Security
      - 부산기능경기대회 웹 디자인 부문 은메달 @고용노동부
      - K-Shield Jr. 11기 멘토

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag


livereload: true

